# Generated by Django 3.2.16 on 2023-03-21 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreequipo', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'db_table': 'equipo',
                'ordering': ['fecha_creacion', 'nombreequipo'],
            },
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretrofeo', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
                ('tipo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.CharField(default='sistemas', max_length=15)),
                ('usuario_modificacion', models.CharField(default='sistemas', max_length=15)),
            ],
            options={
                'verbose_name': 'trofeo',
                'verbose_name_plural': 'trofeos',
                'db_table': 'trofeo',
                'ordering': ['fecha_creacion', 'nombretrofeo'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretorneo', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.CharField(default='sistemas', max_length=15)),
                ('usuario_modificacion', models.CharField(default='sistemas', max_length=15)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muestra.equipo')),
                ('trofeo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muestra.trofeo')),
            ],
            options={
                'verbose_name': 'torneo',
                'verbose_name_plural': 'torneos',
                'db_table': 'torneo',
                'ordering': ['fecha_creacion', 'nombretorneo'],
            },
        ),
    ]
